### ISSUE TITLE
Test Plan quick review

### ISSUE THREAD

**Issue by gderamchi** [algosup/2023-2024-project-5-flutter-team-1#16]
Line 3: "Mattéo LEFIN" should be "Mattéo Lefin." (Names should be consistently capitalized.)
Line 11: "Create documents template" should be "Created document template." (Verb tense consistency is required.)
Line 12: "add sub parts and Table of content" should be "Added sub-parts and Table of Contents." (Capitalization and hyphenation consistency.)
Line 12: "start the writing of" should be "Started writing." (Verb tense consistency is required.)
Line 13: "finish" should be "Finished." (Verb tense consistency is required.)
Line 21: "Table of content" should be "Table of Contents." (Standard term is "Table of Contents.")
Line 24: "Document purpose" should be "Document Purpose." (Capitalization for section titles.)
Line 25: "Project purpose" should be "Project Purpose." (Capitalization for section titles.)
Line 26: "Customer" should be "Customers." (Consistency with plural form as it refers to multiple customers.)
Line 32: "Document criteria" should be "Document Criteria." (Capitalization for section titles.)
Line 33: "Review process" should be "Review Process." (Capitalization for section titles.)
Line 39: "Tests main goal" should be "Tests' Main Goal." (Proper punctuation for possessive form.)
Line 40: "Testing criterias" should be "Testing Criteria." (The plural of "criterion" is "criteria," not "criterias.")
Line 45: "Test management" should be "Testing Management." (Capitalization for section titles.)
Line 105: "Create the test plan" should be "Created document template." (Verb tense consistency and correct line association.)
Line 108: "Create GitHub issues" should be "Created document template." (Verb tense consistency and correct line association.)
Line 114: "5.4 Test deliverables" should have its first point clarified: "Test Plan: It documents our approach and methodology for testing, explaining how tests will be managed and performed." (Clarifying the purpose of the Test Plan.)
Line 117: "5.4 Test deliverables" should have its third point clarified: "GitHub Issues: This section documents any identified issues encountered during the testing phase." (Clarifying the purpose of the GitHub Issues.)
Line 121: "Document approval" should be "Document Approval." (Capitalization for section titles.)
Line 49: "Quality Assurance activity" should be "Quality Assurance activities." (Consistency in plural form to match the context.)
Line 50: "The produced result" should be "the produced results." (Consistency in plural form to match the context.)
Line 50: "The conclusion reached" should be "the conclusions reached." (Consistency in plural form to match the context.)
Line 54: "The project named 'Adopter un candidat' (Adopt a candidate in English) has for purpose" should be "The project named 'Adopter un candidat' (Adopt a Candidate in English) aims to." (Improving clarity and grammatical accuracy.)
Line 57: "It will look like a tab where they will see the different 'matches' of employees, where they accept the candidates and can message them, the new messages will always appear on the top of the tab." should be "It will look like a tab where they will see the different 'matches' of employees, where they can accept the candidates and message them. The new messages will always appear at the top of the tab." (Improving clarity and grammatical accuracy.)
Line 122: "Technical Lead" should be "Technical Lead." (Consistency in capitalization.)
Line 123: "Engineer" should be "Engineer." (Consistency in capitalization.)
Line 54: "Creating an application that allows users to find a job depending primarily on their soft skills." should be "Creating an application that allows users to find a job based primarily on their soft skills." (Improving clarity and grammatical accuracy.)
Line 81: "The coding Software on the left and the emulator on the left" should be "The coding software on the left and the emulator on the right." (Correcting the direction for clarity.)
Line 40: "Ensure that all project criterias are checked" should be "Ensure that all project criteria are met." (The plural of "criterion" is "criteria," not "criterias.")
Line 112: "Test design schema" should be "Test design schema." (Capitalization for section titles.)
Line 105: "Time estimation" should be "Time Estimation." (Consistency in capitalization.)
Line 108: "Review technical specification" should be "Review technical specifications." (Consistency in plural form to match the context.)
Line 111: "Execute the test cases" should be "Execute the test cases." (Verb tense consistency is required.)
Line 112: "Update test cases status" should be "Update test cases status." (Consistency in capitalization and form.)

**Comment by Mattstar64** [comment]
done
