### ISSUE TITLE
Technical Specification Review

### ISSUE THREAD

**Issue by Mattstar64** [algosup/2023-2024-project-5-flutter-team-1#7]
# Technical Specification Review

---

## Description

This github issue has been created to track the problems in the technical document.

## Issues

- l.63 : Typo issue, "candidate's use" --> "**the** candidate's use".
- l.70 : Typo issue "phone and PC application" --> "phone and PC application**s**" .
- l.72 : Typo issue "Some back-end using" --> "Some back-end **use**".
- l.94 : Typo issue, "team is in project-time" --> "team is **on** project-time".
- l.107 : Typo issue, "Avoid to create" --> "Avoid **creating**".
- l.163 : Typo issue, "as part of Google-tested" --> "as part of **the** Google-tested".
- l.181 : Typo issue, "either on Android, IOS and PC" --> "either on Android, IOS **or** PC".
- l.181 : Typo issue, "a certain range of device" --> "a certain range of device**s**.
- l.210 : Typo issue, "can now access to the Developer's" --> "can now access the Developer's".
- l.246 : Typo issue, "Run and debug Flutter code" --> "Run**ing** and debug**ing** Flutter code".
- l.254 : Typo issue, "however you" --> "however, you" (add always a comma after however).
- l.254 : Typo issue, "to create it by yourself" --> "to create **them** yourself".
- l.268 : Typo issue, "if there's no issues" --> "if there **are** no issues".
- l.318 : Typo issue, "contain this lines" --> "contain these lines".
- l.344 : Typo issue, "taking in consideration" --> "taking **into** consideration".
- l.345 : Typo issue, "help us exporting the application" --> "help us **export** the application".
- l.345 : Typo issue, "different device" --> "different device**s**".
- l.347 : Typo issue, "take it coding this" --> "take it **by** coding this".
- l.595 : Typo issue, "to login again" --> "to **log in** again".
- l.632 : Typo issue, "that means" --> "**which** means".
- l.635 : Typo issue, "soft skills match with the company's" --> "soft skills match the company's".
- l.644 : Typo issue, "Both candidate and company's side" --> "Both candidate**'s** and company's side**".
- l.693/695 : Typo issue, "the security" --> "**security**".
- l.695 : Typo issue, "Here's some elements" --> "Here **are** some elements".
- l.699 : Typo issue, "prevent a theft of account " --> "prevent theft of **the** account".
- l.709 :  Typo issue, no need for a comma after "tools".
- l.713 : Typo issue, "Flutter contains few" --> "Flutter contains **a** few".

## Additional comments

- "Folder structure" could include the structure of the documentation document.
- In "Account data flow" you can mix some of the listed information in one, reducing the length and the reader's tiredness (e.g " - the candidates first name and last name".
- in l.181 you can change "There are some requirements that need" by "**Some requirements need**".

**Comment by Mattstar64** [comment]
the issues has been corrected.

**Comment by NanaChocolat** [comment]
- l.133 missing " ``` " before the files structure.
- l.838 missing the word defined in bold.

**Comment by NanaChocolat** [comment]
- You started to put a capital letter in each of your bullet points but didn't capitalise the following lines:
l.693 / l.722 / l.735 / l.761
